version: "3"
services:

#  portainer:
#    container_name: portainer
#    image: portainer/portainer
#    restart: unless-stopped
#    ports: 
#      - 9000:9000


  # https://hub.docker.com/r/diginc/pi-hole/
  # https://github.com/pi-hole/docker-pi-hole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp"
      - "80:80/tcp"
#      - "443:443/tcp"

    # https://github.com/pi-hole/docker-pi-hole#environment-variables
    environment:
      TZ: 'Europe/Rome'
#      WEBPASSWORD: '2212'
      # 192.168.1.1
      # 127.0.0.1
      DNS1: '1.1.1.1' # Used for PiVpn 127.0.0.1
      DNS2: '8.8.8.8' # 8.8.8.8
#      DNSSEC: 'false'
#      DNS_BOGUS_PRIV: 'true'
#      CONDITIONAL_FORWARDING: 'false'
#      ServerIP: '192.168.1.1' # Not required
#      ServerIPv6: ''
#      IPv6: 'true'

    # Volumes store your data between container upgrades
    volumes:
      - './etc-resolv.conf:/etc/resolv.conf'
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'

    # Replaced by copying resolv.conf
#    dns:
#      - '127.0.0.1'
#      - '1.1.1.1'

    # Used for DHCP server
#    cap_add:
#      - NET_ADMIN
